name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4, 8.5]
        orchestra: [9, 10] # Laravel 11, 12
        pest: [3, 4]
        exclude:
          - { php: 8.5, pest: 3 }

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.orchestra == 9 && '11' || '12' }} - Pest ${{ matrix.pest }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, bcmath, pcntl, sqlite
          coverage: pcov

      - name: Install Composer dependencies
        run: |
          composer require --dev \
            "orchestra/testbench:^${{ matrix.orchestra }}" \
            "pestphp/pest:^${{ matrix.pest }}" \
            "pestphp/pest-plugin-laravel:^${{ matrix.pest }}" \
            --no-update --no-interaction
          composer update --prefer-dist --no-progress --no-interaction

      - name: Style check
        run: composer test:lint

      - name: Rector check
        run: composer refactor:dry

      - name: Type check
        run: composer check:types

      - name: Run tests with coverage
        run: composer test:coverage:parallel